export const skills = [
    require("../assets/skillsImages/BEM.png"),
    require("../assets/skillsImages/html-5.png"),
    require("../assets/skillsImages/css.png"),
    require("../assets/skillsImages/sass.png"),
    require("../assets/skillsImages/java-script.png"),
    require("../assets/skillsImages/github.png"),
    require("../assets/skillsImages/react.png"),
    require("../assets/skillsImages/figma.png"),
    require("../assets/skillsImages/java.png"),
    require("../assets/skillsImages/jest.png"),
    require("../assets/skillsImages/Springboot.png"),
    require("../assets/skillsImages/mysql.png"),
    require("../assets/skillsImages/excel.png"),
    require("../assets/skillsImages/word.png"),
    require("../assets/skillsImages/powerpoint.png"),
];

export const softSkills = [
    require("../assets/SoftSkillsImages/communication.png"),
    require("../assets/SoftSkillsImages/deadline.png"),
    require("../assets/SoftSkillsImages/detail.png"),
    require("../assets/SoftSkillsImages/discipline.png"),
    require("../assets/SoftSkillsImages/documenting.png"),
    require("../assets/SoftSkillsImages/focus.png"),
    require("../assets/SoftSkillsImages/independent.png"),
    require("../assets/SoftSkillsImages/leadership.png"),
    require("../assets/SoftSkillsImages/logical.png"),
    require("../assets/SoftSkillsImages/management.png"),
    require("../assets/SoftSkillsImages/mentoring.png"),
    require("../assets/SoftSkillsImages/pressure.png"),
    require("../assets/SoftSkillsImages/problem.png"),
    require("../assets/SoftSkillsImages/team.png"),
    require("../assets/SoftSkillsImages/timekeeping.png"),
];
